// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqpaudbofymqfibtocls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcGF1ZGJvZnltcWZpYnRvY2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDk4MTUsImV4cCI6MjA2MTAyNTgxNX0.tHkmX0Mv4BiU03NLnwQwNDDWeyy0-rUYvwBYpYJTi6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);